live_config_reload = true

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[cursor]
# Set to false to disable completely
smooth_motion = true
# 0.0 = cursor is not moving, 1.0 = cursor moves instantly
smooth_motion_factor = 0.9
# 0.0 = broken, 1.0 = cursor shape is unaffected by movement
smooth_motion_spring = 0.7

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
dynamic_title = true
opacity = 0.3

[window.padding]
x = 20
y = 10
